### ISSUE TITLE
Subtitle isn't on the same height as title

### ISSUE THREAD

**Issue by MrKireko** [eslcc/clubs-list#2]

**Comment by markspolakovs** [comment]
```css
label {
    display: flex;
    align-items: center;
}
```
